services:
  usermanagement-application:
    image: usermanagement-application-image:latest
    container_name: usermanagement-application-1
    ports:
     - "8082:8081"
    depends_on:
     - mysql-db
    networks:
     - user-network
    environment:
     SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/userdb/useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC 
     SPRING_DATASOURCE_USERNAME: root
     SPRING_DATASOURCE_PASSWORD: Root@123
  
  mysql-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    networks:
     - user-network
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: userdb
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  user-network:
    driver: bridge

volumes:
  mysql-data: